### ISSUE TITLE
Transpiling the src to ES5

### ISSUE THREAD

**Issue by declanelcocks** [diegohaz/styled-tools#3]
I'm using `styled-tools` within my project (using your ARc boilerplate), and noticed that in your `.babelrc` you are just targeting the last 2 browsers. When I try to build my app, it ignores `/node_modules/` so it won't try and transpile the source code of this package. Because this package is not transpiling to ES5, UglifyJS is throwing an error because it cannot read the source code and the build will fail. Can you update this package to transpile to ES5? Will also have the same issue with `styled-theme`.

**Comment by diegohaz** [comment]
Hey, @declanelcocks. Could you please copy and paste the UglifyJS error here? Also, what's your NodeJS version?

**Comment by declanelcocks** [comment]
@diegohaz Sure.

```
ERROR in app.d0b2887e9d5bc3a09390.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [app.d0b2887e9d5bc3a09390.js:65390,48]
```

This line in `app.js` is `const get = exports.get .....` from `styled-tools` as it contains an arrow function. My node version is `7.1.0`.

**Comment by diegohaz** [comment]
It's weird, I can't reproduce it. Does it happen on ARc without modifications (clone the repository and `npm run build`)? You are the first person to have problems with that.

**Comment by declanelcocks** [comment]
Yep, I also had the error with just the standard ARc boilerplate

**Comment by diegohaz** [comment]
If you end up concluding that the problem is with `styled-tools`/`styled-theme`, I would accept a PR configuring `babel-preset-env` to fix this. 👍

**Comment by diegohaz** [comment]
@declanelcocks Did you manage to get rid of this or is this still a problem?

**Comment by declanelcocks** [comment]
Sorry I didn't reply to close this as I ran into the issue again yesterday, I haven't found the reason for why it was happening, but I'm 100% sure it's not transpiling of the library which is causing it so it's safe to close this issue.
