### ISSUE TITLE
prop() not setting default

### ISSUE THREAD

**Issue by Moeface** [diegohaz/styled-tools#32]
First off, thanks for the great library! Really cleans up a lot of the boilerplate in our styled components :+1:

I've currently got the following code:

```
const Container = styled.div`
  height: ${prop('height', 'auto')};
`
```
then elsewhere something is using this:
```
const Component = ({ height }) => (
 <Container height={height} />
)

Component.defaultProps = {
  height: null
}
```
Passing something like `400px` into the height prop works fine, but not passing anything gives me this when it's rendered: 
<img width="120" alt="screen shot 2017-09-22 at 11 55 08 am" src="https://user-images.githubusercontent.com/1631699/30726231-f404e39a-9f8c-11e7-90e7-1cc068147c2e.png">

Is this not working properly or am I missing something obvious? Should it not be rendering `height: auto;`?

Thanks again!

**Comment by diegohaz** [comment]
Hi, @Moeface. Glad to know that it's helping you.

The default value is only used if prop is `undefined`. 

`null` or `''` (empty string) are considered valid values. That's how [`lodash's get`](https://lodash.com/docs/4.17.4#get) works, for example (and we are using it here).

**Comment by Moeface** [comment]
No problem, thank you.
