### ISSUE TITLE
Add default case option to switchProp

### ISSUE THREAD

**Issue by nderscore** [diegohaz/styled-tools#34]
I think it might be nice to have a default case option for the `switchProp()` function. Having a generic else case without having to specifically write out every other possible prop value would be nice. Plus, it makes it closer to mirroring the functionality of an actual switch statement! 😉 

I think adding a third optional argument (identical to how `prop()` 's `defaultCase` argument works) would be fine, as it wouldn't break backwards compatibility with current usage of the function.

**Comment by diegohaz** [comment]
Released as [v0.2.3](https://github.com/diegohaz/styled-tools/releases/tag/v0.2.3)

**Comment by nderscore** [comment]
Thanks!

**Comment by mehrad77** [comment]
@diegohaz can this be added to docs?

**Comment by diegohaz** [comment]
@mehrad77 Yes! Would you mind sending a PR updating https://github.com/diegohaz/styled-tools/blob/master/src/switchProp.js and running `npm run docs`
