### ISSUE TITLE
How to get the {palette}Text color ?

### ISSUE THREAD

**Issue by xuopled** [diegohaz/styled-tools#60]
Hello, with a simple palette:
```
export default {
    palette: {
        primary: "#6ab04c",
        primaryText: "#fff",
    }
}
```

If I set the `palette` prop to a component, as your doc mentioned, I can use `background: ${palette()};` to get the palette color. But how can I get the text color? without doing: 

```background: ${props => props.theme.palette[`${props.palette}Text`]};``` 

The following does not work of course:
```background: ${palette(prop(`${props => props.palette)Text`};```

Thank you very much

**Comment by diegohaz** [comment]
Hey @xuopled. There's no concept of text color in styled-tools (I guess you're coming from Reakit? — [it has its own way to do that](https://github.com/reakit/reakit/blob/cf2a93232c56df26c361a1194bf4bc002c9ca41e/packages/reakit/src/_utils/styledProps.ts#L28-L32))

A simple implementation would look like this (which is pretty much what you're doing, but using `withProp`):
```js
const textColorWithProps = withProp("palette", p => palette(`${p}Text`));

const Foo = styled.div`
  background: ${textColorWithProps};
`;
```

**Comment by xuopled** [comment]
Yes, I am coming from `Reakit`. 
Thank you for your help. It's perfect 👌🏻
