### ISSUE TITLE
Is there any way to pass multiple props to an ifProp?

### ISSUE THREAD

**Issue by ncesar** [diegohaz/styled-tools#74]
Example: 

`${ifProp('toggle' and 'pressed', css`background: red;`)`

If the component has toggle and pressed, he should have background red.

**Comment by diegohaz** [comment]
Yes!

```js
ifProp(["toggle", "pressed"], ...)
```

https://github.com/diegohaz/styled-tools#ifprop

**Comment by EJNB** [comment]
if I wanted to do exactly the same thing but with one **or** condition ???
`${ifProp('isActive' or 'isCompleted', ..., ...)}`

**Comment by diegohaz** [comment]
@EJNB You can pass a function to `ifProp`:
```js
ifProp((props) => props.isActive || props.isCompleted, ..., ...)
```
